version: 2
jobs:
  kind:
    machine:
      enabled: true
      # docker_layer_caching: true
      image: circleci/classic:201808-01
    steps:
    - checkout
    - run: 
        name: Install kubectl 
        command: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.3/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin
      
    - run:
        name: Install kubernetes cluster with kind 
        command: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-linux-amd64
          chmod +x kind 
          sudo mv kind /usr/local/bin

    - run:
        name: Install conftest
        command: |
          curl -Lo ./conftest.tar.gz https://github.com/instrumenta/conftest/releases/download/v0.15.0/conftest_0.15.0_Linux_x86_64.tar.gz
          tar xvzf conftest.tar.gz
          sudo mv conftest /usr/local/bin
          conftest --version

    - run:
        name: Install kustomize
        command: |
          curl -Lo ./kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.4.0/kustomize_v3.4.0_linux_amd64.tar.gz
          tar xvzf kustomize.tar.gz
          sudo mv kustomize /usr/local/bin
          kustomize version

    - run:
        name: Start cluster
        command: |
          kind create cluster --name test-cluster --image kindest/node:v1.14.9

    - run:
        name: Waiting for ready
        command: |
          READY=""
          while [ "$READY" != "True" ]
          do
            sleep 2
            READY=`kubectl get node -o=jsonpath='{range .items[*]}{range @.status.conditions[?(@.type == "Ready")]}{@.status}{end}{end}'`
          done
          echo "Node is ready"
          echo "Current running pods are the follows:"
          kubectl get --all-namespaces pod

workflows:
  version: 2
  test:
    jobs:
      - kind 
